AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  laji_project

  Sample SAM Template for laji_project

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Metadata:
  cfn-lint:
    config:
      regions:
        - us-east-1
        - us-east-2
      ignore_checks:
        - E3030
Parameters:
  Env:
    Type: String
    Description: The name of the deployment stage(e.g dev, test, prod)
    Default: Prod

Globals:
  Function:
    Timeout: 3
    Tracing: Active
  Api:
    TracingEnabled: True

Resources:
  PolingestionFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: policy_ingestion/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - arm64
      Events:
        PolicyRequest:
          Type: Api
          Properties:
            Path: /api/v1/policy/create
            Method: POST
            RestApiId: !Ref PolicyIngestionAPI
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - events:PutEvents
              Resource: !GetAtt EventBus.Arn


  PolicyIngestionAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Env
      EndpointConfiguration:
        Type: REGIONAL

  APIKeyPolicyIngestionService:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - PolicyIngestionAPI
    Properties:
      Description: "Key to make API call to policy ingestion engine"
      Enabled: True
      Name: !Sub "APIKeyPolicyIngestionService-${AWS::StackName}"

  PolicyIngestionAPIKeyUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - APIKeyPolicyIngestionService
    Properties:
      ApiStages:
        - ApiId: !Ref PolicyIngestionAPI
          Stage: !Ref PolicyIngestionAPIStage
      Description: "Usage plan to make API call to Ingestion Engine"
      Quota:
        Limit: 10000
        Period: MONTH
      Throttle:
        BurstLimit: 100
        RateLimit: 100


  PolicyIngestionUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref APIKeyPolicyIngestionService
      KeyType: API_KEY
      UsagePlanId: !Ref PolicyIngestionAPIKeyUsagePlan
 

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub "ApplicationInsight-SAM-${AWS::StackName}"
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0
        Query:
          StackIdentifier: !Ref AWS::StackId
  
  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Sub "ApplicationInsight-SAM-${AWS::StackName}"
      AutoConfigurationEnabled: true
    DependsOn: ApplicationResourceGroup
  
  EventBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "PolicyEventBus-${AWS::StackName}"
  
  LifeInsuranceRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "LifeInsuranceRule-${AWS::StackName}"
      Description: "Rule to route life insurance policy data"
      EventBusName: !Ref EventBus
      EventPattern:
        source:
          - laji_project.policydata
        detail:
          policyType:
            - life insurance
      Targets:
        - Arn: !GetAtt LifeInsuranceQueue.Arn
          Id: LifeInsuranceRuleTarget
          RetryPolicy:
            MaximumRetryAttempts: 4
            MaximumEventAgeInSeconds: 400
          DeadLetterConfig:
            Arn: !GetAtt LifeInsuranceDLQ.Arn
      State: ENABLED
  
  AutoInsuranceRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "AutoInsuranceRule-${AWS::StackName}"
      Description: "Rule to route auto insurance policy data"
      EventBusName: !Ref EventBus
      EventPattern:
        source:
          - "laji_project.policydata"
        detail:
          policyType:
            - "auto insurance"
      Targets:
        - Arn: !GetAtt AutoInsuranceQueue.Arn
          Id: AutoInsuranceRuleTarget
          RetryPolicy:
            MaximumRetryAttempts: 4
            MaximumEventAgeInSeconds: 400
          DeadLetterConfig:
            Arn: !GetAtt AutoInsuranceQueueDLQ.Arn
      State: ENABLED
  
  LifeInsuranceQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Sub "LifeInsuranceQueue-${AWS::StackName}"

  LifeInsuranceDLQ:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Sub "LifeInsuranceQueueDLQ-${AWS::StackName}"

  AutoInsuranceQueue:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Sub "AutoInsuranceQueue--${AWS::StackName}"

  AutoInsuranceQueueDLQ:
    Type: 'AWS::SQS::Queue'
    Properties:
      QueueName: !Sub "AutoInsuranceQueueDLQ-${AWS::StackName}"
  
  LifeInsuranceQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Id: PolicyId
        Version: '2012-10-17'
        Statement:
          - Sid: '1'
            Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action:
              - sqs:SendMessage
              - sqs:GetQueueAttributes
              - sqs:GetQueueUrl
            Resource: !GetAtt LifeInsuranceQueue.Arn
      Queues:
        - !Ref LifeInsuranceQueue
  
  AutoInsuranceQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt AutoInsuranceQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref EventBus
      Queues:
        - !Ref AutoInsuranceQueue
  
  LifeInsuranceDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: policyId
          AttributeType: S
      KeySchema:
        - AttributeName: policyId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub "LifeInsuranceDynamoTable-${AWS::StackName}"
  
  AutoInsuranceDynamoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: policyId
          AttributeType: S
      KeySchema:
        - AttributeName: policyId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TableName: !Sub "AutoInsuranceDynamoTable-${AWS::StackName}"
  
  LifeInsuranceLoadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: life_insurance_load/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref LifeInsuranceDynamoTable
          SQS_QUEUE: !Ref LifeInsuranceQueue
      Policies:
        - SQSPollerPolicy:
            QueueName: !Ref LifeInsuranceQueue
  
  AutoInsuranceLoadFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: auto_insurance_load/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - arm64
      Environment:
        Variables:
          DYNAMODB_TABLE: !Ref AutoInsuranceDynamoTable
          SQS_QUEUE: !Ref AutoInsuranceQueue
      Policies:
        - SQSPollerPolicy:
            QueueName: !Ref AutoInsuranceQueue
Outputs:
  PolicyApi:
    Description: API Gateway endpoint URL for Prod stage for Policy Ingestion function
    Value: !Sub "https://${PolicyIngestionAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/v1/policy/new"
  PolingestionFunction:
    Description: Policy Ingestion Lambda Function ARN
    Value: !GetAtt PolingestionFunction.Arn
  PolingestionFunctionIamRole:
    Description: Implicit IAM Role created for Policy Ingestion function
    Value: !GetAtt PolingestionFunctionRole.Arn
  LifeInsuranceQueue:
    Description: SQS Queue URL for Life Insurance
    Value: !GetAtt LifeInsuranceQueue.Arn
  AutoInsuranceQueue:
    Description: SQS Queue URL for Auto Insurance
    Value: !GetAtt AutoInsuranceQueue.Arn
  LifeInsuranceDynamoTable:
    Description: DynamoDB Table Name for Life Insurance
    Value: !Ref LifeInsuranceDynamoTable
  AutoInsuranceDynamoTable:
    Description: DynamoDB Table Name for Auto Insurance
    Value: !Ref AutoInsuranceDynamoTable
  LifeInsuranceLoadFunction:
    Description: Lambda function to load life insurance events to DynamoDB table
    Value: !GetAtt LifeInsuranceLoadFunction.Arn
  AutoInsuranceLoadFunction:
    Description: Lambda function to load auto insurance events to DynamoDB table
    Value: !GetAtt AutoInsuranceLoadFunction.Arn   

